apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080         # Port on which the service is exposed
      targetPort: 8080    # Port inside the container
      nodePort: 30001     # Exposes the service on a specific port on the node
  type: NodePort         # Exposes the service externally via NodePort
